name: Go Build and Release

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: Build
      env:
        CGO_ENABLED: 0
      run: go build -v -o resticara

    - name: Run Tests
      run: go test -v ./...

    - name: Zip artifacts
      run: zip -r resticara-${{ github.ref_name }}.zip resticara config.ini templates/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: resticara-artifacts
        path: resticara-${{ github.ref_name }}.zip

  package:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: resticara-artifacts
    
    - name: Install FPM
      run: sudo apt-get install ruby-dev rubygems build-essential && sudo gem install --no-document fpm

    - name: Create DEB package
      run: fpm -s dir -t deb -n resticara -v ${{ github.ref_name }} --prefix=/usr/local/bin resticara --config-files=/etc/resticara/ config.ini templates/

    - name: Create RPM package
      run: fpm -s dir -t rpm -n resticara -v ${{ github.ref_name }} --prefix=/usr/local/bin resticara --config-files=/etc/resticara/ config.ini templates/

    - name: Upload packaged artifacts
      uses: actions/upload-artifact@v2
      with:
        name: packaged-artifacts
        path: |
          *.deb
          *.rpm

  release:
    needs: package
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: packaged-artifacts

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: Description of the release
        draft: false
        prerelease: false

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./resticara-${{ github.ref_name }}.zip
        asset_name: resticara-${{ github.ref_name }}.zip
        asset_content_type: application/zip

    - name: Upload DEB Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./resticara-${{ github.ref_name }}.deb
        asset_name: resticara-${{ github.ref_name }}.deb
        asset_content_type: application/octet-stream

    - name: Upload RPM Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./resticara-${{ github.ref_name }}.rpm
        asset_name: resticara-${{ github.ref_name }}.rpm
        asset_content_type: application/octet-stream
